from typing import Any, Protocol, Sequence

from arm_memory.domain.models import (
    ConversationTurn,
    GraphEdge,
    MemoryTrace,
    PersonaDefinition,
    ProfileFacetType,
    ProfileItemStatus,
    RelationshipState,
    SemanticFact,
    UserManualSnapshot,
    UserProfile,
    UserProfileItem,
)

class IVectorStore(Protocol):
    @property
    def enabled(self) -> bool: ...

    def ping(self) -> bool: ...

    def ensure_collection(self, *, strict: bool = False) -> None: ...

    def upsert_trace(self, trace: MemoryTrace) -> None: ...

    def search(
        self,
        *,
        project_id: str,
        user_id: str,
        query_vector: list[float],
        limit: int = 10,
    ) -> dict[str, float]: ...

class IGraphStore(Protocol):
    @property
    def enabled(self) -> bool: ...

    def ping(self) -> bool: ...

    def sync_fact(self, fact: SemanticFact) -> None: ...

    def sync_edge(self, edge: GraphEdge) -> None: ...

    def sync_relationship_state(
        self,
        *,
        project_id: str,
        user_id: str,
        companion_node: str,
        state: RelationshipState,
    ) -> None: ...

    def search_related(
        self,
        *,
        project_id: str,
        user_id: str,
        entities: list[str],
        limit: int = 10,
    ) -> dict[str, float]: ...

class IMemoryStore(Protocol):
    def transaction(self) -> Any: ...
    def store_turn(self, turn: ConversationTurn, *, conn: Any = None) -> None: ...
    def list_recent_turns(self, project_id: str, user_id: str, *, limit: int = 50, session_id: str | None = None) -> list[ConversationTurn]: ...
    def mark_turns_consolidated(self, turn_ids: list[str]) -> None: ...
    def add_memory_trace(self, trace: MemoryTrace, *, conn: Any = None) -> None: ...
    def get_trace(self, trace_id: str) -> MemoryTrace | None: ...
    def get_traces_by_ids(self, trace_ids: Sequence[str]) -> list[MemoryTrace]: ...
    def list_active_memory_traces(self, project_id: str, user_id: str) -> list[MemoryTrace]: ...
    def record_memory_access(self, trace_id: str, *, salience_boost: float = 0.0, salience_cap: float = 1.0) -> None: ...
    def apply_semantic_fact(self, fact: SemanticFact, *, conn: Any = None) -> None: ...
    def list_semantic_facts(self, project_id: str, user_id: str) -> list[SemanticFact]: ...
    def save_profile(self, profile: UserProfile, *, conn: Any = None) -> None: ...
    def load_profile(self, project_id: str, user_id: str) -> UserProfile: ...
    def save_profile_item(self, item: UserProfileItem, *, conn: Any = None) -> None: ...
    def list_profile_items(self, project_id: str, user_id: str, facet_type: ProfileFacetType, status: ProfileItemStatus | str | None = None) -> list[UserProfileItem]: ...
    def save_persona(self, persona: PersonaDefinition) -> None: ...
    def list_personas(self, project_id: str, user_id: str) -> list[PersonaDefinition]: ...
    def get_active_persona(self, project_id: str, user_id: str) -> PersonaDefinition | None: ...
    def activate_persona(self, project_id: str, user_id: str, persona_id: str) -> None: ...
    def save_relationship_state(self, state: RelationshipState) -> None: ...
    def load_relationship_state(self, project_id: str, user_id: str) -> RelationshipState: ...
    def save_user_manual(self, snapshot: UserManualSnapshot) -> None: ...
    def load_user_manual(self, project_id: str, user_id: str) -> UserManualSnapshot | None: ...
    def upsert_graph_edge(self, edge: GraphEdge, *, conn: Any = None) -> None: ...
    def enqueue_remote_sync_task(self, *, backend: str, operation: str, project_id: str, user_id: str, payload: dict[str, Any], error_message: str = "", conn: Any = None) -> str: ...
    def claim_remote_sync_tasks(self, *, limit: int = 50, max_attempts: int = 5, reclaim_in_progress_after_seconds: int = 300) -> list[dict[str, object]]: ...
    def mark_remote_sync_task_done(self, task_id: str) -> None: ...
    def mark_remote_sync_task_failed(self, task_id: str, *, error_message: str, max_attempts: int = 5, retry_base_seconds: int = 5, retry_max_seconds: int = 300) -> None: ...
    def get_remote_sync_outbox_summary(self) -> dict[str, int]: ...
    def list_related_nodes(self, project_id: str, user_id: str, start_nodes: list[str], max_depth: int = 2, max_nodes: int = 50) -> list[dict[str, Any]]: ...
    def clear_user_data(self, project_id: str, user_id: str) -> None: ...
    def stats(self, project_id: str, user_id: str) -> dict[str, int]: ...
    def archive_stale_memory_traces(self, project_id: str, user_id: str, before_date: Any) -> int: ...
    def merge_trace_pair(self, keep: MemoryTrace, discard: MemoryTrace, *, conn: Any = None) -> None: ...

from .neo4j_store import Neo4jGraphStore
from .qdrant_store import QdrantVectorStore
from .sqlite_store import SQLiteMemoryStore

__all__ = [
    "IGraphStore",
    "IMemoryStore",
    "IVectorStore",
    "Neo4jGraphStore",
    "QdrantVectorStore",
    "SQLiteMemoryStore",
]
